name: Generate Pipeline

on: [push, pull_request]

permissions: write-all

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for .sh, .go, or .py files
        id: detect
        run: |
          if git ls-files '*.sh' '*.go' '*.py' | grep .; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

          if git ls-files '*.sh' | grep .; then
            echo "projecttype=bash" >> $GITHUB_OUTPUT
          elif git ls-files '*.go' | grep .; then
            echo "projecttype=go" >> $GITHUB_OUTPUT
          elif git ls-files '*.py' | grep .; then
            echo "projecttype=python" >> $GITHUB_OUTPUT
          else
            echo "projecttype=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Copy template if needed
        if: steps.detect.outputs.found == 'true'
        run: |
            if [ "${{ steps.detect.outputs.projecttype }}" == "bash" ]; then
                cp .github/workflows/generated_bash.yml .github/workflows/generated.yml
            elif [ "${{ steps.detect.outputs.projecttype }}" == "go" ]; then
                cp .github/workflows/generated_go.yml .github/workflows/generated.yml
            elif [ "${{ steps.detect.outputs.projecttype }}" == "python" ]; then
                cp .github/workflows/generated_python.yml .github/workflows/generated.yml
            else
                echo "No valid project type found. Aborting."
                exit 1
            fi

      - name: Commit and push if generated.yml changed or is new
        if: steps.detect.outputs.found == 'true'
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .github/workflows/generated.yml
            if git diff --cached --quiet; then
              echo "No changes to commit"
              echo "committed=false" >> $GITHUB_ENV
            else
              git commit -m "chore: add/update generated workflow"
              git push
              echo "committed=true" >> $GITHUB_ENV
            fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Abort workflow if committed
        if: env.committed == 'true'
        run: |
          echo "Workflow updated and committed. Aborting current run."
          exit 1