name: Run Go Program

on: [workflow_call]

jobs:
  called-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: echo "Building the Go program..."