name: Generate Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      should_run1: ${{ steps.setvar.outputs.should_run1 }}
      should_run2: ${{ steps.setvar.outputs.should_run2 }}
    steps:
      - run: |
          mkdir -p ./tmp
          git clone https://github.com/actions/checkout.git ./tmp/checkout

      - uses: ./tmp/checkout
        with:
          repository: GitHub-Accelerate/ga-pipeline-generator
          path: ga-pipeline-generator

      - run: ls && pwd

      - run: ls tmp/checkout

      - run: echo "should_run1=false" >> $GITHUB_OUTPUT

      - run: echo "should_run2=true" >> $GITHUB_OUTPUT

  # https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
  call-workflow1:
    needs: test
    if: needs.test.outputs.should_run1 == 'true'
    uses: ./.github/workflows/generated.yml

  call-workflow2:
    needs: test
    if: needs.test.outputs.should_run2 == 'true'
    uses: ./.github/workflows/generated.yml