name: Generate Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ./tmp
          git clone https://github.com/actions/checkout.git ./tmp/checkout

      - uses: ./tmp/checkout
        with:
          repository: GitHub-Accelerate/ga-pipeline-generator
          path: ga-pipeline-generator

      - run: ls && pwd

      - run: ls tmp/checkout

  # https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
  call-workflow:
    needs: test
    uses: ./.github/workflows/generated.yml