name: Generate Pipeline

on: [push, pull_request]

permissions:
  contents: write

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for .sh, .go, or .py files
        id: detect
        run: |
          if git ls-files '*.sh' '*.go' '*.py' | grep .; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy template if needed
        if: steps.detect.outputs.found == 'true'
        run: |
          cp .github/workflows/generated-template.yml .github/workflows/generated.yml

      - name: Commit and push if generated.yml changed
        if: steps.detect.outputs.found == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet .github/workflows/generated.yml; then
            git add .github/workflows/generated.yml
            git commit -m "chore: update generated workflow"
            git push
            echo "committed=true" >> $GITHUB_ENV
          else
            echo "committed=false" >> $GITHUB_ENV
          fi

      - name: Abort workflow if committed
        if: env.committed == 'true'
        run: |
          echo "Workflow updated and committed. Aborting current run."
          exit 1